services:
  saifDB-dev:
    image: postgres:13
    container_name: saifmarks_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: saifmarks
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  saifDB-test:
    image: postgres:13
    container_name: saifmarks_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: saifmarks_test
    ports:
      - '5435:5432'
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_test:
